AWSTemplateFormatVersion: "2010-09-09"
Description: "EC2 for Windows" 
Resources: 
  IamRoleForWindows:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "Ec2WindowsSsmRoleole"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
Outputs:
  IanRoleForWindowsId:
    Description: "Iam Role ID for Windows"
    Value: !Ref "IamRoleForWindows" 
    Export:
      Name: "IamRoleForWindows"