AWSTemplateFormatVersion: 2010-09-09
Description: "Internet gateway for windows" 
Resources:
  IgwForWindows:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name 
          Value: InternetGatewayForWindows 
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !ImportValue VpcForWindows
      InternetGatewayId: !Ref IgwForWindows 
Outputs:
  IgwForWindows:
    Value: !Ref IgwForWindows
    Export:
      Name: IgwForWindows
