AWSTemplateFormatVersion: "2010-09-09"
Description: "Route table, Route, Route Association for Windows" 
Resources: 
  RouteTableForWindows:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !ImportValue VpcForWindows
      Tags:
        - Key: Name
          Value: RouteTableForWindows

  RouteForWindows:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref RouteTableForWindows
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !ImportValue IgwForWindows

  RouteTableAssociationForWindows:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !ImportValue PublicSubnetForWindows
      RouteTableId: !Ref RouteTableForWindows