AWSTemplateFormatVersion: 2010-09-09
Description: "Security Group for windows"
Resources: 
  SecurityGroupForWindows:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: SecurityGroupForWindows
      GroupDescription: SecurityGroupForWindows 
      VpcId: !ImportValue VpcForWindows
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
Outputs:
  SecurityGroupForWindows:
    Value: !Ref SecurityGroupForWindows 
    Export:
      Name: SecurityGroupForWindows 