AWSTemplateFormatVersion: "2010-09-09"
Description: "Security Group for Windows"
Resources: 
  SecurityGroupForWindows:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: SecurityGroupForWindows
      GroupDescription: Security Group for Windows
      VpcId: !ImportValue VpcForWindows
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 3389 
          ToPort: 3389 
          CidrIp: 0.0.0.0/0
Outputs:
  SecurityGroupForWindowsId:
    Description: "Security Group ID for Windows"
    Value: !Ref SecurityGroupForWindows
    Export:
      Name: SecurityGroupForWindows