AWSTemplateFormatVersion: "2010-09-09"
Description: "Subnet for Windows"
Resources: 
  PublicSubnetForWindows:
    Type: "AWS::EC2::Subnet"
    Properties:
      AvailabilityZone: "ap-northeast-1a"
      VpcId: !ImportValue "VpcForWindows"
      CidrBlock: "10.0.0.0/24"
      Tags:
        - Key: "Name" 
          Value: "PublicSubnetForWindows" 
Outputs:
  PublicSubnetForWindowsId:
    Description: "Public Subnet ID for Windows"
    Value: !Ref "PublicSubnetForWindows" 
    Export:
      Name: !Sub "${AWS::StackName}-PublicSubnetForWindowsId"