AWSTemplateFormatVersion: 2010-09-09
Description: "VPC for windows" 
Resources:
  VpcForWindows:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      Tags:
        - Key: Name 
          Value: VpcForWindows 
Outputs:
  VpcForWindows:
    Value: !Ref VpcForWindows
    Export:
      Name: VpcForWindows
